version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
  pre_build:
    commands:
      - sam build
  build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml