AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SampleProject
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  YourID:
    Type: String
    Default: dummy
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBReadPolicy:
            TableName: YourTableName
      Environment:
        Variables:
          YourID: !Ref YourID
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: POST
Outputs:
  ApiEndpoint:
    Description: "APIGateway Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"